package startup

import (
	"bytes"
	"context"
	"fmt"
	"log"
	"testing"
	"time"
)

func Example() {

	var buf bytes.Buffer
	logger := log.New(&buf, "", 0)

	myMain := func(ctx context.Context, opts *FunctionOptions) {
		logger.Println("starting myMain")
		defer logger.Println("exiting myMain")

		// Emulates doing something
		<-time.After(50 * time.Millisecond)
	}

	StartFunctions(context.Background(), []StartableFunction{
		myMain,
	}, WithLogging(logger, true))

	fmt.Println(&buf)
	// Output:
	// starting myMain
	// exiting myMain
}

func ExampleStartFunctions() {

	mainBoom := func(ctx context.Context, opts *FunctionOptions) {
		<-time.After(50 * time.Millisecond)
		panic("Boom!")
	}

	var buf bytes.Buffer
	logger := log.New(&buf, "", 0)

	StartFunctions(context.Background(), []StartableFunction{
		mainBoom,
	}, WithLogging(logger, true))

	fmt.Println(&buf)
	// Output:
	// caught unhandled panic in (github.com/gford1000-go/startup.ExampleStartFunctions.func1): Boom!
}

func ExampleStartFunctions_second() {

	myMain := func(ctx context.Context, opts *FunctionOptions) {
		defer fmt.Println("myMain exited")

		// Emulate finishing work
		<-time.After(50 * time.Millisecond)
	}
	anotherFn := func(ctx context.Context, opts *FunctionOptions) {
		defer fmt.Println("anotherFn exited as well")

		// Not finished, but will exit
		<-ctx.Done()
	}

	StartFunctions(context.Background(), []StartableFunction{
		myMain,
		anotherFn,
	})

	// Output:
	// myMain exited
	// anotherFn exited as well
}

func ExampleStartFunctions_external_context_done() {

	myFunc := func(ctx context.Context, opts *FunctionOptions) {
		defer fmt.Println("myFunc exited")

		<-ctx.Done() // Busy until told to exit
	}

	ctx, cancel := context.WithTimeout(context.Background(), 100*time.Millisecond)
	defer cancel()

	StartFunctions(ctx, []StartableFunction{
		myFunc,
	})

	// Output:
	// myFunc exited
}

func TestStartFunctions(t *testing.T) {

	err := StartFunctions(context.Background(), nil)

	if err != ErrMissingStartableFunctions {
		t.Fatalf("Expected error: ErrMissingStartableFunctions, got: %v", err)
	}
}

func TestStartNamedFunctions(t *testing.T) {

	err := StartNamedFunctions(context.Background(), nil)

	if err != ErrMissingStartableFunctions {
		t.Fatalf("Expected error: ErrMissingStartableFunctions, got: %v", err)
	}
}

func TestStartNamedFunctions_1(t *testing.T) {

	err := StartNamedFunctions(context.Background(), []FunctionDeclaration{})

	if err != ErrMissingStartableFunctions {
		t.Fatalf("Expected error: ErrMissingStartableFunctions, got: %v", err)
	}
}

func TestStartNamedFunctions_2(t *testing.T) {

	err := StartNamedFunctions(context.Background(), []FunctionDeclaration{
		{},
	})

	if err != ErrFuncMustNotBeNil {
		t.Fatalf("Expected error: ErrFuncMustNotBeNil, got: %v", err)
	}
}

func TestStartNamedFunctions_3(t *testing.T) {

	var name string = "Foo"
	var b bytes.Buffer

	myFunc := func(ctx context.Context, opts *FunctionOptions) {
		b.WriteString(opts.Self)
	}

	err := StartNamedFunctions(context.Background(), []FunctionDeclaration{
		{
			Name: name,
			Func: myFunc,
		},
	})

	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	b1 := b.Bytes()
	if !bytes.Equal(b1, []byte(name)) {
		t.Fatalf("expected name to be the same, got: '%s'", string(b1))
	}
}

func TestStartNamedFunctions_4(t *testing.T) {

	var name string = "Foo"

	myFunc := func(ctx context.Context, opts *FunctionOptions) {
		<-time.After(time.Millisecond)
	}

	err := StartNamedFunctions(context.Background(), []FunctionDeclaration{
		{
			Name: name,
			Func: myFunc,
		},
		{
			Name: name,
			Func: myFunc,
		},
	})

	if err != ErrNameAlreadyExists {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestStartNamedFunctions_5(t *testing.T) {

	var buf bytes.Buffer

	myFunc := func(ctx context.Context, opts *FunctionOptions) {
		buf.WriteString(opts.Self)
		<-time.After(10 * time.Millisecond)
	}

	StartNamedFunctions(context.Background(), []FunctionDeclaration{
		{
			Name: "Foo",
			Func: myFunc,
		},
		{
			Name: "Bar",
			Func: myFunc,
		},
	})

	s := buf.String()
	if s != "FooBar" {
		t.Fatalf("expected 'FooBar', got: %s", s)
	}
}

func TestStartNamedFunctions_6(t *testing.T) {

	var buf bytes.Buffer

	myFunc := func(ctx context.Context, opts *FunctionOptions) {
		buf.WriteString(opts.Self)
	}

	StartNamedFunctions(context.Background(), []FunctionDeclaration{
		{
			Func: myFunc,
		},
	})

	s := buf.String()
	if len(s) == 0 {
		t.Fatal("expected unique name to be autogenerated, but got empty name")
	}
}
